### ISSUE TITLE
Implement Demo in Same Repo

### ISSUE THREAD

**Issue by LanceMcCarthy** [cmancone/akeyless-action#4]
You can run the Action right inside this repo without pulling in anything from the Marketplace, just do `uses: ./`. This means you don't don't need a separate repository that you have to maintain on top of this one :)

Here's a real world use where I run my Actions on every commit: https://github.com/LanceMcCarthy/Action-AzureBlobUpload/blob/main/.github/workflows/main_release.yml 

Here's what I imagine yours would eventually look like:

```yaml
name: 'Main and Releases'

on:
  push:
    branches:
      - main
      - 'v*'

jobs:
  package_and_run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          rimraf lib
          tsc
          eslint src/**/*.ts
          ncc build --source-map --license licenses.txt
          jest --coverage

# verify everything works without needing to be compiled/packaged
  fetch_static_secrets:
    runs-on: ubuntu-latest
    name: Fetch some static secrets
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Fetch static secrets from AKeyless
        id: fetch-static-secrets
        uses: ./   # IMPORTANT - this references './' instead of the Marketplace's listing
        with:
          access-id: p-jiu4ebrbyalq
          static-secrets: '{"/MyFirstSecret":"my_first_secret"}'
          export-secrets-to-outputs: true
          export-secrets-to-environment: true
          
      - name: Output your secret (this should be masked in logs and terminal output)
        run: echo "Your secret is ${{ steps.fetch-static-secrets.outputs.my_first_secret }}"
```

I am going to include this for you in a couple PRs I have planned for later today (I was able to fix #2, will be pushing that soon)
